env:
  contexts:
    - name: buildwiselabs
      urls:
        - https://buildwiselabs.net
  parameters:
    failOnError: true

jobs:
  - type: spider
    parameters:
      maxDuration: 5

  - type: passiveScan-wait

  - type: activeScan
    parameters:
      maxRuleDurationInMins: 2

  - type: report
    parameters:
      template: traditional-html
      reportFile: reporte.html
  - type: report
    parameters:
      template: traditional-md
      reportFile: reporte.md
  - type: forced-report
    parameters:
      template: traditional-json
      reportFile: reporte.json